services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LOGGER=zap
      - ETCD_LOG_LEVEL=error
    networks:
      - inner_network
    ports:
      - "2379:2379"

  # webpage:
  #   image: nginx:latest
  #   ports:  
  #     - "80:80"
  #   volumes:
  #     - ./webpage/nginx.conf:/etc/nginx/nginx.conf
  #     - ./webpage/html:/html
  #   networks:
  #     - inner_network
  #   # depends_on:
  #   #   - api
  
  postgres:
    image: postgres:14
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - inner_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: always
  #   networks:
  #     - inner_network
    
  # user:
  #   build:
  #     context: rpc/user
  #     dockerfile: ../../docker/service.dockerfile 
  #   environment:
  #     - ETCD_ENDPOINT=http://etcd:2379
  #   networks:
  #     - inner_network 
  #   ports:
  #     - "10001:10001"
  #   depends_on:
  #     - etcd

networks:
  inner_network: