services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LOGGER=zap
      - ETCD_LOG_LEVEL=error
    networks:
      - inner_network
    ports:
      - "2379:2379"
    logging:
      driver: "none"

  api:
    build: 
      context: api
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
    ports:
      - "8888:8888"
    networks:
      - inner_network 
    depends_on:
      - etcd
      - user

  webpage:
    image: nginx:latest
    ports:  
      - "80:80"
    volumes:
      - ./webpage/nginx.conf:/etc/nginx/nginx.conf
      - ./webpage/html:/html
    networks:
      - inner_network
    depends_on:
      - api

  user:
    build:
      context: rpc/user
      dockerfile: ../../docker/service.dockerfile 
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
    networks:
      - inner_network 
    ports:
      - "10001:10001"
    depends_on:
      - etcd

networks:
  inner_network: